-- DROP TABLE IF EXISTS users_roles;
-- DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
ROLE_ID bigint(5) AUTO_INCREMENT,
NAME int(5),
PRIMARY KEY(ROLE_ID)
);

 
CREATE TABLE users (
USER_ID bigint(5) AUTO_INCREMENT,
USERNAME varchar(100) NOT NULL UNIQUE,
PASSWORD varchar(25) NOT NULL,
EMAIL varchar(100) NOT NULL UNIQUE,
DATE_ADHESION_DEBUT DATE NOT NULL, 
DATE_ADHESION_FIN DATE, 
DATE_BLOCAGE_DEBUT DATE, 
DATE_BLOCAGE_FIN DATE,
PRIMARY KEY(USER_ID)
);



  

  
CREATE TABLE user_roles (
user_id bigint(20) NOT NULL,
role_id bigint(20) NOT NULL,
FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE RESTRICT ON UPDATE CASCADE,
PRIMARY KEY (user_id, role_id)
);  




  
